### ISSUE TITLE
colorscheme shows only white background in macvim

### ISSUE THREAD

**Issue by mooreniemi** [Sclarki/neonwave.vim#1]
I'd like to be able to use this colorscheme in gui and in regular terminal. But currently, the background color is not respected and I only ever see white. I've seen this as an issue in previous themes. Can you help?

**Comment by Sclarki** [comment]
I don't use macvim, so I cannot say for sure what the issue would be.


Just to be clear, it is white in both GUI and terminal? If it were only GUI Vim then I would think it is due to a lack of gui colours in the theme. Also, is it all themes you have trouble with, or only certain ones?

**Comment by mooreniemi** [comment]
@Sclarki only certain themes (just yours so far) doesnt render in macvim correctly. it works just fine in terminal, fwiw.

**Comment by Sclarki** [comment]
That is likely due to lack of GUI colour support. I only use Vim in terminal and I've yet to implement any full colour support in the theme itself.

At some point it will be there. I would also accept a PR, as well!

**Comment by Sclarki** [comment]
Let me know if this fixes it.

**Comment by TobalJackson** [comment]
I've tried out the current neonwave.vim on gvim 8.0 and it works as intended (black background, supercharged colors).
