### ISSUE TITLE
Doesn't work properly with gvim

### ISSUE THREAD

**Issue by thrisp** [Sclarki/neonwave.vim#4]
I tried this scheme -- only seems to render properly with vim, but not gvim.

I'm not entirely certain how to debug something like this at this point.
![neonwave](https://cloud.githubusercontent.com/assets/199137/11003022/5623298c-847e-11e5-9d8c-80694a7c4b6c.png)

**Comment by Sclarki** [comment]
I believe the colour support should be there now. If it isn't, however, let me know.
